import Navbar from "@/components/main";
import Head from "next/head";
import favicon from "../public/favicon.ico";
import About from "@/components/pages/About";
import Menu from "@/components/pages/Menu";
import Footer from "@/components/pages/Footer";
import { ProfileInfo } from "@/components/pages/About";
import { AboutHeadline } from "@/components/pages/About";

export default function Home() {
	return (
		<>
			<Head>
				<title>Marco Restaurant</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" type="image/x-icon" href={favicon.src} />
			</Head>
			<Navbar />
			<main>
				<AboutHeadline />
				<Menu />
				<ProfileInfo />
			</main>
			<Footer />
		</>
	);
}
